version: '3'

services:
  analysis:
    env_file:
      - common.env
      - database.env
      - analysis.env
      - dynamic.env

    image: "${IMAGE_URL}/comsearch-analysis:${IMAGE_TAG}"

    ports:
      - '8080:8080'

    environment:
      SERVER_PORT: 8080
      AMAZON_STACKNAME: "${STACK}"
      JAVA_TOOL_OPTIONS: >
        -XX:OnError='kill -TERM %p'
        -XX:+CrashOnOutOfMemoryError
        -verbose:gc
        -XX:+PrintGCDetails
        -Dnetworkaddress.cache.ttl=20
        -Dsun.net.client.defaultConnectTimeout=30000
        -Dsun.net.client.defaultReadTimeout=590000
        -Djasypt.encryptor.algorithm=PBEWithMD5AndDES
        -Djasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

    logging:
      driver: awslogs
      options:
        awslogs-group: "${COMPOSE_PROJECT_NAME}-${STACK}"
        awslogs-create-group: 'true'
        awslogs-stream: "${COMPOSE_FILE}-${INSTANCE_ID}"

#    healthcheck:
#      test: 'curl --connect-timeout 3 --max-time 15 --fail http://localhost:8080/analysis/application-version'

# vim: expandtab:ts=4:sw=2
