version: '3'

services:
  frontend:
    env_file:
      - frontend.env

    image: "${IMAGE_URL}/<image-name>:${IMAGE_TAG}"

    ports:
      - '80:80'

    environment:
      AMAZON_STACKNAME: "${STACK}"

    logging:
      driver: awslogs
      options:
        awslogs-group: "${COMPOSE_PROJECT_NAME}-${STACK}"
        awslogs-create-group: 'true'
        awslogs-stream: "${COMPOSE_FILE}-${INSTANCE_ID}"

    healthcheck:
      test: 'nc -z localhost 80'
#      test: 'curl --connect-timeout 3 --max-time 15 --fail http://localhost:80/'

# vim: expandtab:ts=4:sw=2
